name: Terraform CI - Pipeline Central

on:
  pull_request:
    branches:
      - main

jobs:

  analisis:
    name: Llamar analisis estatico y seguridad
    uses: ./.github/workflows/tflint-checkov.yml
    with:
      path: terraform/

  validacion:
    name: Llamar validacion Terraform
    needs: analisis
    uses: ./.github/workflows/validate.yml
    with:
      path: terraform/